### ISSUE TITLE
The results on the GQA-OOD dataset.

### ISSUE THREAD

**Issue by yswness** [chojw/genb#10]
Dear chojw,

Hello,
I noticed in your paper that your method achieved a result of 49.43 on GQA-OOD, which is an impressive outcome! However, I have a question: is this result obtained on the GQA-OOD validation set or on the GQA-OOD test-dev set? 
Thank you and I look forward to your response!

Best regards,
yswness

**Comment by chojw** [comment]
Hi, as I recall, we followed the protocol listed here https://github.com/gqa-ood/GQA-OOD
I believe the results should be the GQA-OOD test .
Thanks!
