### ISSUE TITLE
VQA-v2

### ISSUE THREAD

**Issue by ghost** [chojw/genb#12]
Dear Author, did you try to run the VQA-v2 dataset Test-dev or Test-std with your model?

**Comment by chojw** [comment]
Hi, 
We list our VQA-v2 validation scores on the VQA-CE set. 
Since VQA-CE and VQA-v2 val is the same set. 
![image](https://github.com/user-attachments/assets/54e0607b-63a4-4000-bb06-597f39528a92)
As far as I remember, we do not have official scores on the VQA-v2 Test-dev or Test-std set.
Thanks!

**Comment by ghost** [comment]
ok，thanks
