### ISSUE TITLE
The torch version is low

### ISSUE THREAD

**Issue by attackon1point6** [chojw/genb#6]
I want to run the code on 3090 or A100, but I find the code use torch 1.2.0, and the GPU driver is too high.
When I use torch 1.7.1, there is an error:RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 1]], which is output 0 of TBackward, is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
It occurs at the second gradient backward(train the discriminator).
So did anyone run successfully in version 1.7.1?

**Comment by attackon1point6** [comment]
I have sloved.Calculate the generator loss first and backward but not step, and then step after the discriminator calculates the loss.

**Comment by Larry2000error** [comment]
Did you reproduce the effect it claimed to have?

**Comment by XiaozhenQiao** [comment]
> I have sloved.Calculate the generator loss first and backward but not step, and then step after the discriminator calculates the loss.

Can you Share your code,thank you.

**Comment by attackon1point6** [comment]
> Did you reproduce the effect it claimed to have?
Yes I did.The score I run is 59.17.

**Comment by attackon1point6** [comment]
> Did you reproduce the effect it claimed to have?

Yes I did.The score I run is 59.17.

**Comment by attackon1point6** [comment]
> > I have sloved.Calculate the generator loss first and backward but not step, and then step after the discriminator calculates the loss.
> 
> Can you Share your code,thank you.

in for:
...
            # get model output
            optim.zero_grad()
            pred = model(v, q)

            # train genb
            optim_G.zero_grad()

            pred_g = genb(v, q, gen=True)
            g_loss = F.binary_cross_entropy_with_logits(pred_g, a, reduction='none').mean()
            # g_loss *= a.size(1)
            g_loss = g_loss * a.size(1)

            vae_preds = discriminator(pred_g)
            main_preds = discriminator(pred)

            optim_D.zero_grad()
            dsc_loss_d = bce(vae_preds, fake) + bce(main_preds, valid)
            dsc_loss_d.backward(retain_graph=True)
            # optim_D.step()

            g_distill = kld(pred_g, pred.detach())
            dsc_loss_g = bce(vae_preds, valid) + bce(main_preds, valid)

            # g_loss += dsc_loss + g_distill*5
            g_loss = g_loss + dsc_loss_g + g_distill * 5
            g_loss.backward(retain_graph=True)
            nn.utils.clip_grad_norm_(genb.parameters(), 0.25)
            optim_D.step()
            optim_G.step()
            # done training genb

**Comment by XiaozhenQiao** [comment]
> > > I have sloved.Calculate the generator loss first and backward but not step, and then step after the discriminator calculates the loss.
> > 
> > 
> > Can you Share your code,thank you.
> 
> in for: ... # get model output optim.zero_grad() pred = model(v, q)
> 
> ```
>         # train genb
>         optim_G.zero_grad()
> 
>         pred_g = genb(v, q, gen=True)
>         g_loss = F.binary_cross_entropy_with_logits(pred_g, a, reduction='none').mean()
>         # g_loss *= a.size(1)
>         g_loss = g_loss * a.size(1)
> 
>         vae_preds = discriminator(pred_g)
>         main_preds = discriminator(pred)
> 
>         optim_D.zero_grad()
>         dsc_loss_d = bce(vae_preds, fake) + bce(main_preds, valid)
>         dsc_loss_d.backward(retain_graph=True)
>         # optim_D.step()
> 
>         g_distill = kld(pred_g, pred.detach())
>         dsc_loss_g = bce(vae_preds, valid) + bce(main_preds, valid)
> 
>         # g_loss += dsc_loss + g_distill*5
>         g_loss = g_loss + dsc_loss_g + g_distill * 5
>         g_loss.backward(retain_graph=True)
>         nn.utils.clip_grad_norm_(genb.parameters(), 0.25)
>         optim_D.step()
>         optim_G.step()
>         # done training genb
> ```

Thank you for reply, but I still have that BUG, maybe my torch version is too high(2.0.1),so I want to use torch==1.7.1, but My cuda version is 12.2 . Can you tell me your CUDA version ? Thanks again!

**Comment by attackon1point6** [comment]
> > > > I have sloved.Calculate the generator loss first and backward but not step, and then step after the discriminator calculates the loss.
> > > 
> > > 
> > > Can you Share your code,thank you.
> > 
> > 
> > in for: ... # get model output optim.zero_grad() pred = model(v, q)
> > ```
> >         # train genb
> >         optim_G.zero_grad()
> > 
> >         pred_g = genb(v, q, gen=True)
> >         g_loss = F.binary_cross_entropy_with_logits(pred_g, a, reduction='none').mean()
> >         # g_loss *= a.size(1)
> >         g_loss = g_loss * a.size(1)
> > 
> >         vae_preds = discriminator(pred_g)
> >         main_preds = discriminator(pred)
> > 
> >         optim_D.zero_grad()
> >         dsc_loss_d = bce(vae_preds, fake) + bce(main_preds, valid)
> >         dsc_loss_d.backward(retain_graph=True)
> >         # optim_D.step()
> > 
> >         g_distill = kld(pred_g, pred.detach())
> >         dsc_loss_g = bce(vae_preds, valid) + bce(main_preds, valid)
> > 
> >         # g_loss += dsc_loss + g_distill*5
> >         g_loss = g_loss + dsc_loss_g + g_distill * 5
> >         g_loss.backward(retain_graph=True)
> >         nn.utils.clip_grad_norm_(genb.parameters(), 0.25)
> >         optim_D.step()
> >         optim_G.step()
> >         # done training genb
> > ```
> 
> Thank you for reply, but I still have that BUG, maybe my torch version is too high(2.0.1),so I want to use torch==1.7.1, but My cuda version is 12.2 . Can you tell me your CUDA version ? Thanks again!

12.2,too.

**Comment by Larry2000error** [comment]
Have you checked the loss of the GAN during the training process? My experiments tell me that this GAN is almost untrainable, and the excellent results are purely due to the base model.

**Comment by Larry2000error** [comment]
> Have you checked the loss of the GAN during the training process? My experiments tell me that this GAN is almost untrainable, and the excellent results are purely due to the base model.
You can take a look at the issue I mentioned in this ticket; mode collapse occurred during the GAN training process.
[https://github.com/chojw/genb/issues/8](url)

**Comment by nlynpp** [comment]
> > Did you reproduce the effect it claimed to have?
> 
> Yes I did.The score I run is 59.17.

Can I ask if you have made any other adjustments, according to your code I am only running results up and down to 58.4.
