### ISSUE TITLE
The pattern collapse during training

### ISSUE THREAD

**Issue by Larry2000error** [chojw/genb#8]
Hi, I am reproducing this work of yours, I had to make some modifications to your code to get it to run due to different hardware drivers. The changes are as follows: 

1. I modified the position of optim_G.step() to move it before optim_D.step().

but I found that I could not reproduce your results. I have examined the code and found that the problem lies in the training of the GAN, I found that following your code when running on my hardware a pattern collapse occurs, i.e. the generator's loss starts close to 0.However discriminator losses are very high. Here the gen_loss and dsc_loss I have recorded using the code shown below:
![f3c2321d71a7b80c12064f1b4aad120](https://github.com/chojw/genb/assets/66721209/a43d3383-5853-4ad8-9017-f896c3f9850c)
![44356cab6c5f5d0ccdc32dac138abc4](https://github.com/chojw/genb/assets/66721209/1a014f44-3006-4585-8ed1-fe86db40b0dd)

![8f727a1398c920d8ac85225df8adc38](https://github.com/chojw/genb/assets/66721209/b59956b1-34cb-433d-999a-f3d374799338)

 I would like to ask you if you have encountered this problem in your implementation? If not, can you please spot where my problem occurs?

**Comment by chojw** [comment]
Hi, it seems there are some issues that are coming from version differences. and another issue seems to have been discussing this. Please refer to issue 6.
